```{r}
library(knitr)
library(dplyr)
library(reshape2)
library(magrittr)
###Load CHAS data
###Includes all needed Tables
x <- 'Fayetteville city, North Carolina'
options(scipen = 999)
```

```{r}
setwd("C:/Users/UDV-5/Documents")
Table1 <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table1.csv", header=TRUE, sep=",") 
Table2 <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table2.csv", header=TRUE, sep=",")
Table3 <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table3.csv", header=TRUE, sep=",")
Table5 <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table5.csv", header=TRUE, sep=",")
Table7 <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table7.csv", header=TRUE, sep=",")
Table8 <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table8.csv", header=TRUE, sep=",")
Table9 <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table9.csv", header=TRUE, sep=",")
Table10 <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table10.csv", header=TRUE, sep=",")
Table13 <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table13.csv", header=TRUE, sep=",")
Table16 <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table16.csv", header=TRUE, sep=",")
Table15A <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table15A.csv", header=TRUE, sep=",")
Table15B <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table15B.csv", header=TRUE, sep=",")
Table15C <- read.csv(file="2012thru2016-155-csv/2012thru2016-155-csv/155/Table15C.csv", header=TRUE, sep=",")
```
```{r}
###Load Data Dictionaries
setwd("C:/Users/UDV-5/Documents")
dict_filepath <- "2012thru2016-155-csv/2012thru2016-155-csv/155/CHAS data dictionary 12-16.xlsx"
data_dictionary1 <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 1")
names(data_dictionary1) <-c(gsub('/', '_', names(data_dictionary1)))
data_dictionary2 <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 2")
names(data_dictionary2) <-c(gsub('/', '_', names(data_dictionary1)))
data_dictionary3 <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 3")
data_dictionary5 <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 5")
data_dictionary7 <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 7")
data_dictionary8 <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 8")
data_dictionary9 <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 9") 
names(data_dictionary9) <-c(gsub('/', '_', names(data_dictionary9)))
data_dictionary10 <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 10")
data_dictionary13 <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 13")
data_dictionary16 <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 16")
data_dictionary15A <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 15A")
data_dictionary15B <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 15B")
data_dictionary15C <- readxl::read_xlsx(path = dict_filepath, sheet = "Table 15C")
```

```{r Get filtering categories}
TenureCategories <- unique(data_dictionary1$Tenure)
Oneof4Categories <- unique(data_dictionary1$`1 of 4 housing problems`)
SevereCategories <- unique(data_dictionary2$`1 of 4 severe housing problems`)
S2 <- c(SevereCategories[2], SevereCategories[3], SevereCategories[4])
Severity3Categories <- unique(data_dictionary3$`Housing problem severity, ordered`)
S32 <- c(Severity3Categories[2], Severity3Categories[3], Severity3Categories[4], Severity3Categories[5], Severity3Categories[6], Severity3Categories[7], Severity3Categories[8])
ElderlyCategories <- unique(data_dictionary5$`Elderly occupant`)
E2 <- c(ElderlyCategories[2], ElderlyCategories[3])
HouseholdCategories <- unique(data_dictionary7$`Household type`)
H2 <- c(HouseholdCategories[3], HouseholdCategories[4])
H2_30 <- c(HouseholdCategories[3], HouseholdCategories[4], HouseholdCategories[5], HouseholdCategories[6])
HAMFICategories7 <- unique(data_dictionary7$`Household income`)
HAMFICategories <- unique(data_dictionary1$`Household income`)
RaceCategories <- unique(data_dictionary9$Race_ethnicity)
R2 <- c(RaceCategories[2], RaceCategories[3], RaceCategories[4], RaceCategories[5], RaceCategories[6], RaceCategories[7])
BurdenCategories7 <- unique(data_dictionary7$`Cost burden`)
BurdenCategories <- unique(data_dictionary9$`Cost burden`)
FacilitiesCategories <- unique(data_dictionary8$Facilities)
PPRCategories <- unique(data_dictionary10$`Persons per room`)
FamilyCategories <- unique(data_dictionary10$`Family type`)
F2 <- c(FamilyCategories[2], FamilyCategories[3], FamilyCategories[4])
Oneof4_16Categories <- unique(data_dictionary16$`Housing problems`)
ChildrenCategories <- unique(data_dictionary13$Children)
YearCategories <- unique(data_dictionary13$`Year structure was built`)
```

```{r}
##Use to prepare for cast function
OrganizeCHAS <- function(table, dict, x){
  place_filter <- filter(table, grepl(x, name, fixed = TRUE))
  dictionary_filter <- dict %>% filter(Line_Type == 'Detail')
  d <- colnames(place_filter)
  data <- as.data.frame(t(rbind(place_filter, d)))
  names(data) <- c('Estimate', 'Column Name')
  joined <- left_join(dictionary_filter, data, by = 'Column Name') %>%
    mutate(Estimate=droplevels(Estimate)) %>% mutate_if(is.factor, as.character)
  joined[,ncol(joined)] <- as.numeric(joined$Estimate)
  joined
}

OrganizeCHAS3 <- function(table, dict, x){
  place_filter <- filter(table, grepl(x, name, fixed = TRUE))
  dictionary_filter <- dict %>% filter(Line_Type != 'Total')
  d <- colnames(place_filter)
  data <- as.data.frame(t(rbind(place_filter, d)))
  names(data) <- c('Estimate', 'Column Name')
  joined <- left_join(dictionary_filter, data, by = 'Column Name') %>%
    mutate(Estimate=droplevels(Estimate)) %>% mutate_if(is.factor, as.character)
  joined[,ncol(joined)] <- as.numeric(joined$Estimate)
  joined
}
```

```{r Number of households table}
t7_1 <- OrganizeCHAS3(Table7, data_dictionary7, x) %>% filter(`Household type` != 'All')
t7_2 <- dcast(t7_1, `Household type`~`Household income`, sum)
totalrow <- c('Total Households', colSums(t7_2[2:6]))
t7_3 <- rbind(totalrow, t7_2 %>% slice(match(H2, `Household type`))) 
kable(t7_3[,c(1, 6, 3, 4, 5, 2)]) 
```

```{r Number of households table part 2}
t5_1 <- OrganizeCHAS3(Table5, data_dictionary5, x) %>% filter(`Elderly occupant` != 'All')
t5_2 <- dcast(t5_1, `Elderly occupant`~`Household income`, sum) %>% slice(match(E2, `Elderly occupant`))
kable(t5_2[,c(1, 6, 3, 4, 5, 2)])
```

```{r Number of households with Children}
t13_1 <- OrganizeCHAS3(Table13, data_dictionary13, x) %>% filter(Children==ChildrenCategories[2])
t13_2 <- dcast(t13_1, Children~`Household income`, sum)
kable(t13_2[,c(1, 6, 3, 4, 5, 2)])
```

```{r Housing Problems Summary Table}
t3_1 <- OrganizeCHAS3(Table3, data_dictionary3, x)
t3_2 <- dcast(t3_1, `Housing problem severity, ordered`~`Household income`+Tenure, sum)
t3_3 <- tail(t3_2, 6) %>% slice(match(S32, `Housing problem severity, ordered`))
kable(t3_3[,c(1, 13, 7, 9, 11, 3, 12, 6, 8, 10, 2)])
```

```{r Severe Problems Summary Table}
t2_1 <- OrganizeCHAS3(Table2, data_dictionary2, x)
t2_2 <- dcast(t2_1, `1 of 4 housing problems`~`Household income`+Tenure, sum) 
S2 <- c(t2_2$`1 of 4 housing problems`[3], t2_2$`1 of 4 housing problems`[4], t2_2$`1 of 4 housing problems`[2])
t2_3 <- tail(t2_2, 3) %>% slice(match(S2, `1 of 4 housing problems`))
kable(t2_3[,c(1, 13, 7, 9, 11, 3, 12, 6, 8, 10, 2)])
```

```{r Cost Burdens by Household Type -- one table for each income}
t7_1_30 <- OrganizeCHAS3(Table7, data_dictionary7, x) %>% filter(`Cost burden`==BurdenCategories7[2])
t7_2_30 <- dcast(t7_1_30, `Household type`~Tenure+`Household income`, sum) %>% tail(4)
TColumn <- dcast(t7_1_30, `Household type`~Tenure, sum) %>% tail(4)
OColumns <- t7_2_30[1:6]
RColumns <- t7_2_30[7:11]
t7_2_30 <- cbind(OColumns, TColumn[2], RColumns, TColumn[3])
totalrow <- c('Total need by income', colSums(t7_2_30[2:13]))
t7_3_30 <- rbind(t7_2_30 %>% slice(match(H2_30, `Household type`)), totalrow)
kable(t7_3_30[,c(1, 12, 9, 10, 13, 6, 3, 4, 7)])

t7_1_50 <- OrganizeCHAS3(Table7, data_dictionary7, x) %>% filter(`Cost burden`==BurdenCategories7[4])
t7_2_50 <- dcast(t7_1_50, `Household type`~Tenure+`Household income`, sum) %>% tail(4)
TColumn <- dcast(t7_1_50, `Household type`~Tenure, sum) %>% tail(4)
OColumns <- t7_2_50[1:6]
RColumns <- t7_2_50[7:11]
t7_2_50 <- cbind(OColumns, TColumn[2], RColumns, TColumn[3])
totalrow <- c('Total need by income', colSums(t7_2_50[2:11]))
t7_3_50 <- rbind(t7_2_50 %>% slice(match(H2_30, `Household type`)), totalrow) 
kable(t7_3_50[,c(1, 12, 9, 10, 13, 6, 3, 4, 7)])
```

```{r Crowding by household type}
t10_1 <- OrganizeCHAS3(Table10, data_dictionary10, x) %>% filter(`Persons per room`==PPRCategories[3] | `Persons per room`==PPRCategories[4])
t10_2 <- dcast(t10_1, `Family type`~Tenure+`Household income`, sum) %>% tail(3)
TColumn <- dcast(t10_1, `Family type`~Tenure, sum) %>% tail(3)
OColumns <- t10_2[1:7]
RColumns <- t10_2[8:13]
t10_2 <- cbind(OColumns, TColumn[2], RColumns, TColumn[3])
totalrow <- c('Total need by income', colSums(t10_2[2:15]))
t10_3 <- rbind(t10_2 %>% slice(match(F2, `Family type`)), totalrow) 
kable(t10_3[,c(1, 14, 11, 12, 13, 15, 7, 4, 5, 6, 8)])
```

```{r Crowding with Children by household type}
t13_1 <- OrganizeCHAS3(Table13, data_dictionary13, x) %>% filter(Children==ChildrenCategories[2])
t13_2 <- dcast(t13_1, Children~Tenure+`Household income`, sum)
TColumn <- dcast(t13_1, Children~Tenure, sum)
OColumns <- t13_2[1:6]
RColumns <- t13_2[7:11]
t13_2 <- cbind(OColumns, TColumn[2], RColumns, TColumn[3])
kable(t13_2[,c(1, 12, 9, 10, 11, 13, 6, 3, 4, 5, 7)])
```

```{r Percent amounts for CHAS}
t1_1 <- OrganizeCHAS(Table1, data_dictionary1, x)
t1_2 <- dcast(t1_1, Race_ethnicity~`1 of 4 housing problems`, sum)
BaseRow <- rowSums(t1_2[2:4])
TotalTotal <- as.numeric(sum(BaseRow))
t1_3 <- cbind(BaseRow, t1_2)
AIndianTotal <- as.numeric(t1_3[1,1])
AsianTotal <- as.numeric(t1_3[2,1])
BlackTotal <- as.numeric(t1_3[3,1])
HispanicTotal <- as.numeric(t1_3[4,1])
OtherTotal <- as.numeric(t1_3[5,1])
PITotal <- as.numeric(t1_3[6,1])
WhiteTotal <- as.numeric(t1_3[7,1])

z <- round(WhiteTotal/TotalTotal*100,2)
```


```{r Housing Problems by Race -- one table for each income}
t1_1_30 <- OrganizeCHAS(Table1, data_dictionary1, x) %>% filter(`Household income`==HAMFICategories[2])
t1_2_30 <- dcast(t1_1_30, Race_ethnicity~`1 of 4 housing problems`, sum)
totalrow <- c('Jurisdiction as a Whole', colSums(t1_2_30[2:4]))
t1_3_30 <- rbind(totalrow, t1_2_30)
t1_4_30 <- rbind(totalrow, t1_2_30 %>% slice(match(R2, Race_ethnicity)))
kable(t1_4_30[,c(1, 3, 4, 2)])

t1_1_50 <- OrganizeCHAS(Table1, data_dictionary1, x) %>% filter(`Household income`==HAMFICategories[3])
t1_2_50 <- dcast(t1_1_50, Race_ethnicity~`1 of 4 housing problems`, sum)
totalrow <- c('Jurisdiction as a Whole', colSums(t1_2_50[2:4]))
t1_3_50 <- rbind(totalrow, t1_2_50)
t1_4_50 <- rbind(totalrow, t1_2_50 %>% slice(match(R2, Race_ethnicity)))
kable(t1_4_50[,c(1, 3, 4, 2)])

t1_1_80 <- OrganizeCHAS(Table1, data_dictionary1, x) %>% filter(`Household income`==HAMFICategories[4])
t1_2_80 <- dcast(t1_1_80, Race_ethnicity~`1 of 4 housing problems`, sum)
totalrow <- c('Jurisdiction as a Whole', colSums(t1_2_80[2:4]))
t1_3_80 <- rbind(totalrow, t1_2_80)
t1_4_80 <- rbind(totalrow, t1_2_80 %>% slice(match(R2, Race_ethnicity)))
kable(t1_4_80[,c(1, 3, 4, 2)])

t1_1_100 <- OrganizeCHAS(Table1, data_dictionary1, x) %>% filter(`Household income`==HAMFICategories[5])
t1_2_100 <- dcast(t1_1_100, Race_ethnicity~`1 of 4 housing problems`, sum)
totalrow <- c('Jurisdiction as a Whole', colSums(t1_2_100[2:4]))
t1_3_100 <- rbind(totalrow, t1_2_100)
t1_4_100 <- rbind(totalrow, t1_2_100 %>% slice(match(R2, Race_ethnicity)))
kable(t1_4_100[,c(1, 3, 4, 2)])
```



```{r Severe Housing Problems by Race -- one table for each income}
t2_1_30 <- OrganizeCHAS(Table2, data_dictionary2, x) %>% filter(`Household income`==HAMFICategories[2])
t2_2_30 <- dcast(t2_1_30, Race_ethnicity~`1 of 4 housing problems`, sum)
totalrow <- c('Jurisdiction as a Whole', colSums(t2_2_30[2:4]))
t2_3_30 <- rbind(totalrow, t2_2_30)
t2_4_30 <- rbind(totalrow, t2_2_30 %>% slice(match(R2, Race_ethnicity)))
kable(t2_4_30[,c(1, 3, 4, 2)])

t2_1_50 <- OrganizeCHAS(Table2, data_dictionary2, x) %>% filter(`Household income`==HAMFICategories[3])
t2_2_50 <- dcast(t2_1_50, Race_ethnicity~`1 of 4 housing problems`, sum)
totalrow <- c('Jurisdiction as a Whole', colSums(t2_2_50[2:4]))
t2_3_50 <- rbind(totalrow, t2_2_50)
t2_4_50 <- rbind(totalrow, t2_2_50 %>% slice(match(R2, Race_ethnicity)))
kable(t2_4_50[,c(1, 3, 4, 2)])

t2_1_80 <- OrganizeCHAS(Table2, data_dictionary2, x) %>% filter(`Household income`==HAMFICategories[4])
t2_2_80 <- dcast(t2_1_80, Race_ethnicity~`1 of 4 housing problems`, sum)
totalrow <- c('Jurisdiction as a Whole', colSums(t2_2_80[2:4]))
t2_3_80 <- rbind(totalrow, t2_2_80)
t2_4_80 <- rbind(totalrow, t2_2_80 %>% slice(match(R2, Race_ethnicity)))
kable(t2_4_80[,c(1, 3, 4, 2)])

t2_1_100 <- OrganizeCHAS(Table2, data_dictionary2, x) %>% filter(`Household income`==HAMFICategories[5])
t2_2_100 <- dcast(t2_1_100, Race_ethnicity~`1 of 4 housing problems`, sum)
totalrow <- c('Jurisdiction as a Whole', colSums(t2_2_100[2:4]))
t2_3_100 <- rbind(totalrow, t2_2_100)
t2_4_100 <- rbind(totalrow, t2_2_100 %>% slice(match(R2, Race_ethnicity)))
kable(t2_4_100[,c(1, 3, 4, 2)])
```


```{r Race by HAMFI calculations}
t9_1 <- OrganizeCHAS(Table9, data_dictionary9, x)
t9_2 <- dcast(t9_1, Race_ethnicity~`Cost burden`, sum)
totalrow <- c('Jurisdiction as a Whole', colSums(t9_2[2:5]))
t9_3 <- rbind(totalrow, t9_2)
```

```{r Race by HAMFI table}
t9_4 <- rbind(totalrow, t9_2 %>% slice(match(R2, Race_ethnicity)))
kable(t9_4[,c(1, 4, 2, 3, 5)])
```


```{r}
###Not what I want. Try 15A, 15B, and 15C.
t17A_1 <- OrganizeCHAS(Table17A, data_dictionary17A, x)
t17A_2 <- dcast(t17A_1, `Asking price`~Line_Type, sum)
```

```{r Risk of Lead Paint Hazard}
###Need to make total row
t13L_1 <- OrganizeCHAS3(Table13, data_dictionary13, x) %>% filter(`Year structure was built`!=YearCategories[2]) %>% na.omit
t13L_2 <- dcast(t13L_1, Children~Tenure, sum)
kable(t13L_2[,c(1, 2, 3)])
```
